### ISSUE TITLE
route traffic to containers without using host level ports

### ISSUE THREAD

**Issue by homeyer** [waffleio/takeout-nginx#22]
Currently, Takeout requires you to open up ports 3000-3009 on the host machine for nginx to be able to route traffic to different containers.

We should be able to route traffic without opening up ports on the host machine. Not quite sure how though :).

**Acceptance Criteria**
- [x] Waffle Takeout works with ports 3001-3009 closed on the host machine

**Comment by dennis-johnson-dev** [comment]
merge order
- hedwig
- takeout-nginx
- replicated (with new images from above)

**Comment by songawee** [comment]
test
